### PR TITLE
Cyan: Update 8042 driver & handle wifi suspend

### PR DESCRIPTION
**Pull request by danielstuart14**
Should fix all keyboard issues when going to tablet mode. (Key spam when pressed)

### CODE REVIEW

**Comment by MrChromebox** [comment]
I just updated the cyan branch with the latest upstream commits, please rebase your branch/PR on top of it

**Comment by danielstuart14** [comment]
built and tested, should be gtg

**Comment by danielstuart14** [comment]
However, userspace still expects a key release event after a key is pressed, which may not happen when keyboard is disabled (Ex: when entering tablet mode or when rebooting the ec), and thus, it could cause a key to get stuck and spam the user, until any other event is registered.
This is an issue with mainline, and the fix may be backported once it's done. But for now, these commits mitigate the issue.

**Comment by danielstuart14** [comment]
Issue 100% fixed with latest commit

**Comment by danielstuart14** [comment]
Cyan keyboard didn't like the backported debounce commit, sometimes shift + a key would not trigger it (if typing fast). I've been testing it for some time, should be fine now without this commit.

**Pull request closed without merging**
